### ISSUE TITLE
Supervisor fails to run deeply nested executables

### ISSUE THREAD

**Issue by bitsandscraps** [aiwc/test_world#55]
The limit seems to be 4.

examples/A/executable.py -> WORKS PERFECT
examples/A/B/executable.py -> FAILS with the following error

> [supervisor] execve failed: No such file or directory
[supervisor] terminate called after throwing an instance of 'std::runtime_error'
[supervisor]   what():  one of the given executables does not exist, or cannot run

**Comment by chshong** [comment]
Sorry for the late reply. We have observed the issue.

The issue was on parsing the executable path in 'controllers/supervisor/game.cpp'. In Lines 422 and 433, replacing 'ti.executable' with 'p_exe.filename().string()' will resolve the issue.

This fix will be applied to our repository on next release.

Thank you for the notification.
